//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 09:54:38 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://moerks.dk/soapws/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dk.moerks.soapws.schemas;
